### ISSUE TITLE
setup.sh checks the gcc version incorrectly

### ISSUE THREAD

**Issue by Habitante5079** [lronaldo/cpctelera#142] opened 2021-09-05 13:45 UTC
My gcc version is 10
setup.sh returns
"CPCtelera requires GCC 4.0 or greater. Please, update your GCC version and run setup again."

function versionGreaterOREqualThan() {
...
if [[ "$VTH_DIGIT" > "$V_DIGIT" ]]; then
...
}

it checks the gcc version incorrectly, compare both variables as String. 
"4" > "10" -> true
It should be changed ">" by "-gt" 
or
[[ "$VTH_DIGIT" > "$V_DIGIT" ]]
by
(( "$VTH_DIGIT" > "$V_DIGIT" ))

**Comment by lronaldo** [comment] 2021-09-06 09:33
Hi @Habitante5079,

Thanks for the report. This issue was fixed 15 months ago and the fix is in master branch. The problem is only present on the old release of CPCtelera 1.4.2 if you download the ZIP release file (which is much older).

If you want to use CPCtelera stable, download current git repo and use current master banch. However, it is usually much recommended to download git repo and switch to 1.5 development branch. This new branch is currently under development, but stable for general usage purposes and will probably be published as new release in next months.

Thank you in any case for reporting. That's always welcome :)

**Closed by lronaldo** 2021-09-06 09:33 UTC
Labels: duplicate
