### ISSUE TITLE
can't build the development branch in osx

### ISSUE THREAD

**Issue by johnlobo** [lronaldo/cpctelera#80] opened 2018-08-30 20:33 UTC
When trying to build the development branch, during the execution of "setup.sh", In the section "checking important files" , an unrecoverable error stops the build...

#########################
#########################
##> file '/Users/david/Documents/retro/proyectos/cpctelera/cpctelera/tools/scripts/templates/newprj/cfg/build_config.mk'  does not exist, and it is required for CPCTelera framework to work propperly. 

Operating System: MacOs High Sierra ver.10.13.6

**Comment by patxoca** [comment] 2018-08-30 21:27
Same error here on ubuntu 16.04. I think that `"${CPCT_TEMPLATES_CFG}"`can be safely removed from `setup.sh` on line 118 since the file it references is created on line 356.

Doing that I've got past that error but now I get a compilation error. Log attached.
[tool_building.log](https://github.com/lronaldo/cpctelera/files/2337950/tool_building.log)

I'm a bit confused, the branch with all the new goodies is `master` or `development`?

**Comment by fidergo-stephane-gourichon** [comment] 2018-08-31 05:28
> build_config.mk' does not exist, and it is required for CPCTelera framework to work propperly.

Reproduced here, on Ubuntu 16.04 here.

Agreed with @patxoca 

The file names by `"${CPCT_TEMPLATES_CFG}"` is created a little later, from the file named by `"${CPCT_TEMPLATES_CFG_TMPL}"` which is mentioned on line 115.

> Doing that I've got past that error but now I get a compilation error. Log attached.
tool_building.log

I see. Treating all warnings as errors on code that compiles with warnings.

> I'm a bit confused, the branch with all the new goodies is master or development?

It depends on what you call "goodies". Goodies start with things not tested enough yet. :-)

**Comment by cpcitor** [comment] 2018-08-31 05:36
Opened pull request #81.
https://github.com/lronaldo/cpctelera/pull/81

**Comment by lronaldo** [comment] 2018-08-31 06:14
Thank you @johnlobo @patxoca for reporting and @cpcitor for so fast reviewing :). You all did this while I was sleeping :+1: 

> I see. Treating all warnings as errors on code that compiles with warnings.

Yes, the idea is forcing gcc to tell everything and not leave a single potential problem. However, the problem raises when compiling with different gcc versions: sometimes there are warnings/errors that are only raised by some versions. 

I think that I will be wise to maintain -Wall -pedantic switches, but remove -Werror.

**Comment by lronaldo** [comment] 2018-08-31 06:47
I have merged @cpcitor's patch and also reviewed other Makefiles to remove `-Werror` and ensure that warnings from previous GCC versions are not a problem to get CPCtelera up and running.

Please, check that setup now works as expected and you can start using development branch.

Thank you for your collaboration to all :+1:

**Closed** 2018-08-31 06:47 UTC
Labels: bug
